export const PROJECTS = [
  {
    id: 0,
    client: '7-Eleven Norway',
    focus:
      'Creative direction, illustration language, concept development, illustration',
    path: '/projects/1-7eleven-LillaBardenova.mp4',
    type: 'video',
  },
  {
    id: 1,
    client: 'Uber',
    focus: 'Branding, campaign creation, product marketing support',
    path: '/projects/2-Uber-LillaBardenova.png',
    type: 'image',
  },
  {
    id: 2,
    client: 'Snapchat',
    focus: 'Creative direction, concept development, lettering, illustration',
    path: '/projects/3-Snapchat-LillaBardenova.gif',
    type: 'image',
  },
  {
    id: 3,
    flower: true,
    path: '',
  },
  {
    id: 4,
    client: 'Voxbone',
    focus: 'Branding, web design, campaign creation',
    path: '/projects/4-Voxbone-LillaBardenova.mp4',
    type: 'video',
  },
  {
    id: 5,
    client: 'Udemy',
    focus: 'Creative direction, character development, illustration',
    path: '/projects/5-Udemy-LillaBardenova.png',
    type: 'image',
  },
  {
    id: 6,
    client: 'Facebook',
    focus: 'Creative direction, character development, illustration, animation',
    path: '/projects/6-Facebook-LillaBardenova.mp4',
    type: 'video',
  },
  {
    id: 7,
    client: 'Deepcrawl',
    focus: 'Campaign creation, product marketing support',
    path: '/projects/7-Deepcrawl-LillaBardenova.png',
    type: 'image',
  },
  {
    id: 8,
    client: 'Bandwidth',
    focus: 'Brand consistency, web design, product marketing support',
    path: '/projects/8-Bandwidth-LillaBardenova.mp4',
    type: 'video',
  },
  {
    id: 9,
    client: 'Certainly',
    focus: 'Creative direction, character development, illustration',
    path: '/projects/9-Certainly-LillaBardenova.mp4',
    type: 'video',
  },
  {
    id: 10,
    client: 'GoDaddy',
    focus: 'Concept development, character creation, illustration, animation',
    path: '/projects/10-GoDaddy-LillaBardenova.mp4',
    type: 'video',
  },
];
